# Business Understanding

The Product Subcategories table contains the subcategories assigned to each product category.

It is used to organize products into a hierarchical structure and enables detailed sales analysis at the subcategory level.

This table connects the Product Categories table with the Products table and will later be used in the Power BI data model.

# 1. Load the Dataset

In [18]:
import pandas as pd 
import numpy as np

subcategories = pd.read_csv("C:/Users/singh/OneDrive/Desktop/AdventureWorks_Analytics/data/raw/AdventureWorks_Product_Subcategories.csv")

# 2. Data Profiling

In [19]:
subcategories.head()
subcategories.tail()

    ProductSubcategoryKey  SubcategoryName  ProductCategoryKey
32                     33           Lights                   4
33                     34            Locks                   4
34                     35         Panniers                   4
35                     36            Pumps                   4
36                     37  Tires and Tubes                   4

In [20]:
subcategories.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 37 entries, 0 to 36
Data columns (total 3 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   ProductSubcategoryKey  37 non-null     int64
 1   SubcategoryName        37 non-null     object
 2   ProductCategoryKey     37 non-null     int64
dtypes: int64(2), object(1)
memory usage: 1020.0+ bytes

In [21]:
subcategories.shape

(37, 3)

In [22]:
subcategories.isnull().sum()

ProductSubcategoryKey    0
SubcategoryName          0
ProductCategoryKey       0
dtype: int64

In [23]:
subcategories.dtypes

ProductSubcategoryKey     int64
SubcategoryName          object
ProductCategoryKey        int64
dtype: object

In [24]:
subcategories.duplicated().sum()

np.int64(0)

# 3. Data Quality Assessment
- No missing values found.
- No duplicate records found.
- No datatype issues identified.
- No inconsistent values detected.
- Column names will be standardized to `snake_case` for consistency across the project.

**Conclusion:** The Product Subcategories dataset is clean and requires only minor formatting before loading into the ETL pipeline.

# 4. Data Cleaning

In [25]:
subcategories.head()

   ProductSubcategoryKey  SubcategoryName  ProductCategoryKey
0                      1   Mountain Bikes                   1
1                      2       Road Bikes                   1
2                      3    Touring Bikes                   1
3                      4       Handlebars                   2
4                      5  Bottom Brackets                   2

In [26]:
subcategories.columns = subcategories.columns.str.strip()

In [27]:
subcategories = subcategories.rename(columns={
    "ProductSubcategoryKey": "product_subcategory_key",
    "ProductCategoryKey": "product_category_key",
    "SubcategoryName": "subcategory_name"
})

In [28]:
subcategories['subcategory_name']= subcategories['subcategory_name'].str.strip()

In [29]:
subcategories.head()

   product_subcategory_key subcategory_name  product_category_key
0                        1   Mountain Bikes                     1
1                        2       Road Bikes                     1
2                        3    Touring Bikes                     1
3                        4       Handlebars                     2
4                        5  Bottom Brackets                     2

In [30]:
subcategories.isnull().sum()

product_subcategory_key    0
subcategory_name           0
product_category_key       0
dtype: int64

In [31]:
subcategories.shape

(37, 3)

In [32]:
subcategories.nunique()

product_subcategory_key    37
subcategory_name           37
product_category_key        4
dtype: int64

# 4. Export Clean Dataset

In [33]:
subcategories.to_csv("C:/Users/singh/OneDrive/Desktop/AdventureWorks_Analytics/data/cleaned/subcategories_clean.csv",
                     index=False)