# Business Understanding

The Territories table contains geographical information about sales regions.

This table is used to analyze sales performance by country, region, and continent. It will later be connected to the Sales table using **TerritoryKey** to support geographic reporting and Power BI dashboards.

# 01. Load the Dataset

In [1]:
import pandas as pd 
import numpy as np

territories = pd.read_csv("C:/Users/singh/OneDrive/Desktop/AdventureWorks_Analytics/data/raw/AdventureWorks_Territories.csv")

In [2]:
territories.head()

   SalesTerritoryKey     Region        Country      Continent
0                  1  Northwest  United States  North America
1                  2  Northeast  United States  North America
2                  3    Central  United States  North America
3                  4  Southwest  United States  North America
4                  5  Southeast  United States  North America

# 2. Data Profiling

In [19]:
territories.head()
territories.tail()

   SalesTerritoryKey          Region         Country      Continent
5                  6          Canada          Canada  North America
6                  7          France          France         Europe
7                  8         Germany         Germany         Europe
8                  9       Australia       Australia        Pacific
9                 10  United Kingdom  United Kingdom         Europe

In [20]:
territories.duplicated().sum()

np.int64(0)

In [21]:
territories.shape

(10, 4)

In [22]:
territories.isnull().sum()

SalesTerritoryKey    0
Region               0
Country              0
Continent            0
dtype: int64

In [23]:
territories.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   SalesTerritoryKey  10 non-null     int64
 1   Region             10 non-null     object
 2   Country            10 non-null     object
 3   Continent          10 non-null     object
dtypes: int64(1), object(3)
memory usage: 452.0+ bytes

# 3. Data Quality Assessment

- No missing values found.
- No duplicate records found.
- No datatype issues identified.
- No inconsistent values detected.
- Column names will be standardized to `snake_case` for consistency across the project.

**Conclusion:** The Territories dataset is clean and requires only minor formatting before loading into the ETL pipeline.

# 4. Data Cleaning

In [24]:
territories.head()

   SalesTerritoryKey     Region        Country      Continent
0                  1  Northwest  United States  North America
1                  2  Northeast  United States  North America
2                  3    Central  United States  North America
3                  4  Southwest  United States  North America
4                  5  Southeast  United States  North America

In [25]:
territories.columns = territories.columns.str.strip().str.lower()

In [26]:
territories = territories.rename(columns={'salesterritorykey':'sales_territory_key'})

In [27]:
text_columns = territories.select_dtypes('object').columns

for col in text_columns:
    territories[col] = territories[col].str.strip()

In [28]:
territories.head()

   sales_territory_key     region        country      continent
0                    1  Northwest  United States  North America
1                    2  Northeast  United States  North America
2                    3    Central  United States  North America
3                    4  Southwest  United States  North America
4                    5  Southeast  United States  North America

In [29]:
territories.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   sales_territory_key  10 non-null     int64
 1   region               10 non-null     object
 2   country              10 non-null     object
 3   continent            10 non-null     object
dtypes: int64(1), object(3)
memory usage: 452.0+ bytes

In [30]:
territories.isnull().sum()

sales_territory_key    0
region                 0
country                0
continent              0
dtype: int64

In [31]:
territories.shape

(10, 4)

In [32]:
territories.nunique()

sales_territory_key    10
region                 10
country                 6
continent               3
dtype: int64

# 04. Export Clean Data

In [33]:
territories.to_csv("C:/Users/singh/OneDrive/Desktop/AdventureWorks_Analytics/data/cleaned/territories_clean.csv",
                   index=False)