#  Business Understanding

The Calendar table contains date-related attributes used for time-based analysis.

It enables reporting by year, quarter, month, and day, allowing business users to analyze sales trends over time.

This table will later be connected to the Sales table using the order date.

# 1. Load the Dataset

In [19]:
import pandas as pd 
import numpy as np

calendar = pd.read_csv("C:/Users/singh/OneDrive/Desktop/AdventureWorks_Analytics/data/raw/AdventureWorks_Calendar.csv")

# 2. Data Profiling

In [20]:
calendar.head()
calendar.tail()

          Date
907  6/26/2017
908  6/27/2017
909  6/28/2017
910  6/29/2017
911  6/30/2017

In [21]:
calendar.shape

(912, 1)

In [22]:
calendar.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 912 entries, 0 to 911
Data columns (total 1 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Date    912 non-null    object
dtypes: object(1)
memory usage: 7.3+ KB

In [23]:
calendar.isnull().sum()

Date    0
dtype: int64

In [24]:
calendar.duplicated().sum()

np.int64(0)

# 3. Data Quality Assesment

- No missing values found.
- No duplicate records found.
- Date values were reviewed for consistency.
- Column names will be standardized to `snake_case` for consistency across the project.

**Conclusion:** The Calendar dataset is clean and requires only minor formatting before loading into the ETL pipeline.

# 4. Data Cleaning

In [25]:
calendar.head()

       Date
0  1/1/2015
1  1/2/2015
2  1/3/2015
3  1/4/2015
4  1/5/2015

In [26]:
calendar.columns = calendar.columns.str.lower()

In [27]:
calendar['date'] = pd.to_datetime(calendar['date'],errors='coerce')

In [28]:
calendar.isnull().sum()

date    0
dtype: int64

In [29]:
calendar.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 912 entries, 0 to 911
Data columns (total 1 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    912 non-null    datetime64[ns]
dtypes: datetime64[ns](1)
memory usage: 7.3 KB

In [30]:
calendar.duplicated().sum()

np.int64(0)

# 5. Feature Engineering

Additional date attributes are created from the `date` column to support time-based analysis in SQL and Power BI.

These derived columns improve reporting by enabling analysis by year, quarter, month, week, day, and weekend.

In [31]:
calendar['year'] = calendar['date'].dt.year
calendar['quarter'] ='Q' + calendar['date'].dt.quarter.astype(str)
calendar['month'] = calendar['date'].dt.month_name()
calendar['month_num'] = calendar['date'].dt.month
calendar['day'] = calendar['date'].dt.day
calendar['day_name']= calendar['date'].dt.day_name()
calendar['week'] = calendar['date'].dt.isocalendar().week.astype(int)
calendar['day_of_year']= calendar['date'].dt.day_of_year
calendar['is_weekend'] = calendar['day_name'].isin(["Saturday","Sunday"])

In [32]:
calendar.head()

,date,year,quarter,month,month_num,day,day_name,week,day_of_year,is_weekend
0,2015-01-01,2015,Q1,January,1,1,Thursday,1,1,False
1,2015-01-02,2015,Q1,January,1,2,Friday,1,2,False
2,2015-01-03,2015,Q1,January,1,3,Saturday,1,3,True
3,2015-01-04,2015,Q1,January,1,4,Sunday,1,4,True
4,2015-01-05,2015,Q1,January,1,5,Monday,2,5,False

In [33]:
calendar.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 912 entries, 0 to 911
Data columns (total 10 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   date         912 non-null    datetime64[ns]
 1   year         912 non-null    int32
 2   quarter      912 non-null    object
 3   month        912 non-null    object
 4   month_num    912 non-null    int32
 5   day          912 non-null    int32
 6   day_name     912 non-null    object
 7   week         912 non-null    int64
 8   day_of_year  912 non-null    int32
 9   is_weekend   912 non-null    bool
dtypes: bool(1), datetime64[ns](1), int32(4), int64(1), object(3)
memory usage: 50.9+ KB

# 6. Export Clean Data

In [34]:
calendar.to_csv("C:/Users/singh/OneDrive/Desktop/AdventureWorks_Analytics/data/cleaned/calendar_clean.csv"
,index=False)