#  Business Understanding

The Returns dataset contains information about products returned by customers.

This table is used to analyze return trends, product quality issues, regional return rates, and overall business performance.

It will be linked with the Products, Territories, and Calendar dimension tables to support return analysis in SQL and Power BI.

# 1. Load Dataset

In [33]:
import pandas as pd 
import numpy as np

returns = pd.read_csv("C:/Users/singh/OneDrive/Desktop/AdventureWorks_Analytics/data/raw/AdventureWorks_Returns.csv")

# 2. Data Profiling

In [34]:
returns.head()

  ReturnDate  TerritoryKey  ProductKey  ReturnQuantity
0  1/18/2015             9         312               1
1  1/18/2015            10         310               1
2  1/21/2015             8         346               1
3  1/22/2015             4         311               1
4   2/2/2015             6         312               1

In [35]:
returns.shape

(1809, 4)

In [36]:
returns.columns

Index(['ReturnDate', 'TerritoryKey', 'ProductKey', 'ReturnQuantity'], dtype='object')

In [37]:
returns.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1809 entries, 0 to 1808
Data columns (total 4 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   ReturnDate      1809 non-null   object
 1   TerritoryKey    1809 non-null   int64
 2   ProductKey      1809 non-null   int64
 3   ReturnQuantity  1809 non-null   int64
dtypes: int64(3), object(1)
memory usage: 56.7+ KB

In [38]:
returns.isnull().sum()

ReturnDate        0
TerritoryKey      0
ProductKey        0
ReturnQuantity    0
dtype: int64

In [39]:
returns.duplicated().sum()

np.int64(0)

In [40]:
returns.describe(include='all')

       ReturnDate  TerritoryKey   ProductKey  ReturnQuantity
count        1809   1809.000000  1809.000000     1809.000000
unique        476           NaN          NaN             NaN
top      6/7/2017           NaN          NaN             NaN
freq           12           NaN          NaN             NaN
mean          NaN      6.259812   443.460475        1.010503
std           NaN      2.948103   115.326651        0.101973
min           NaN      1.000000   214.000000        1.000000
25%           NaN      4.000000   369.000000        1.000000
50%           NaN      7.000000   479.000000        1.000000
75%           NaN      9.000000   529.000000        1.000000
max           NaN     10.000000   606.000000        2.000000

In [41]:
returns.nunique()

ReturnDate        476
TerritoryKey        8
ProductKey        124
ReturnQuantity      2
dtype: int64

# 3. Data Quality Assessment

- No missing values found.
- No duplicate records found.
- Column names will be standardized to `snake_case`.
- `return_date` will be converted to datetime format.
- The dataset is clean and requires only minor transformations before loading into the data warehouse.

**Conclusion:** The Returns dataset has good data quality and is ready for ETL processing.

# 4. Data Cleaning

In [42]:
returns.columns = (
    returns.columns
    .str.strip()
    .str.replace(" ","_")
    .str.replace(r'(?<!^)(?=[A-Z])',"_",regex=True)
    .str.lower()
)

In [43]:
returns.columns

Index(['return_date', 'territory_key', 'product_key', 'return_quantity'], dtype='object')

In [44]:
returns['return_date'] = pd.to_datetime(returns['return_date'],errors='coerce')

In [45]:
returns.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1809 entries, 0 to 1808
Data columns (total 4 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   return_date      1809 non-null   datetime64[ns]
 1   territory_key    1809 non-null   int64
 2   product_key      1809 non-null   int64
 3   return_quantity  1809 non-null   int64
dtypes: datetime64[ns](1), int64(3)
memory usage: 56.7 KB

In [46]:
returns["return_quantity"].describe()

count    1809.000000
mean        1.010503
std         0.101973
min         1.000000
25%         1.000000
50%         1.000000
75%         1.000000
max         2.000000
Name: return_quantity, dtype: float64

In [47]:
returns.dtypes

return_date        datetime64[ns]
territory_key               int64
product_key                 int64
return_quantity             int64
dtype: object

In [48]:
returns.head()

  return_date  territory_key  product_key  return_quantity
0  2015-01-18              9          312                1
1  2015-01-18             10          310                1
2  2015-01-21              8          346                1
3  2015-01-22              4          311                1
4  2015-02-02              6          312                1

# 6. Export Clean Data

In [49]:
returns.to_csv("C:/Users/singh/OneDrive/Desktop/AdventureWorks_Analytics/data/cleaned/returns_clean.csv"
             ,index=False)